// lib/api.ts — Real API client for GridWitness (v2 — handles envelope + flat shapes)
// Tolerates both /api/telemetry/live response shapes:
//   A) Flat array:        [{...}, {...}]
//   B) Envelope:          {records: [{...}, {...}]}
// And both field naming conventions:
//   New: gCO2e, Actual_Wattage, Timestamp, InfraType
//   Old: CarbonDebt_gCO2, ActualWattage, SealedAt, DataSource

const API_BASE = process.env.NEXT_PUBLIC_API_URL ||
                 'https://rdof7lrwfj.execute-api.ca-central-1.amazonaws.com'

// ──────────────────────────────────────────────────────────────────────────
// Types
// ──────────────────────────────────────────────────────────────────────────
export interface TelemetryRecord {
  TenantID:        string
  Timestamp:       string
  Source:          string
  GridID:          string
  Actual_Wattage:  number
  InfraType?:      string
  gCO2e:           number
  // Legacy aliases kept for components that read old names directly
  ActualWattage?:    number
  CarbonDebt_gCO2?:  number
  DataSource?:       string
  SealedAt?:         string
  CarbonIntensity?:  number
  SHA256Hash?:       string
}

export interface Incident {
  TenantID:         string
  IncidentID:       string
  GridID:           string
  Metric:           string
  Status:           'OPEN' | 'CLOSED'
  Severity?:        'WARNING' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
  BreachValue:      number
  PeakValue?:       number
  Threshold:        number
  OpenedAt:         string
  ClosedAt?:        string
  LastAction?:      string
  LastActionAt?:    string
  // Set by incident manager from SQS payload
  Title?:           string
  Description?:     string
  Source?:          string
  AutoGenerated?:   boolean
  ObservationCount?: number
  AutoCloseValue?:  number
}

export interface GridSnapshot {
  GridID:           string
  CurrentIntensity?: number
  CarbonIntensity?:  number
  Source?:          string
  UpdatedAt?:       string
  PoolPrice?:       number
  DataQuality?:     string
}

// ──────────────────────────────────────────────────────────────────────────
// Defaults
// ──────────────────────────────────────────────────────────────────────────
export const DEFAULT_GRID_THRESHOLDS: Array<{
  gridId: string; carbonAlert: number; loadAlert: number; priceAlert: number
}> = [
  { gridId: 'AB', carbonAlert: 600, loadAlert: 85, priceAlert: 300 },
  { gridId: 'ON', carbonAlert: 100, loadAlert: 85, priceAlert: 200 },
  { gridId: 'BC', carbonAlert:  50, loadAlert: 85, priceAlert: 200 },
  { gridId: 'QC', carbonAlert:  20, loadAlert: 85, priceAlert: 200 },
]

// ──────────────────────────────────────────────────────────────────────────
// Fetch helper
// ──────────────────────────────────────────────────────────────────────────
async function gwFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const r = await fetch(`${API_BASE}${path}`, {
    ...init,
    headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) },
    cache: 'no-store',
  })
  if (!r.ok) {
    let detail = ''
    try { detail = (await r.json()).error || '' } catch {}
    throw new Error(detail || `HTTP ${r.status} ${r.statusText}`)
  }
  return r.json() as Promise<T>
}

// Unwrap response — tolerates flat array, {records:[...]}, {items:[...]}, {data:[...]}
function unwrapList(raw: unknown): Array<Record<string, unknown>> {
  if (Array.isArray(raw)) return raw as Array<Record<string, unknown>>
  if (raw && typeof raw === 'object') {
    const obj = raw as Record<string, unknown>
    for (const key of ['records', 'items', 'data', 'results']) {
      if (Array.isArray(obj[key])) return obj[key] as Array<Record<string, unknown>>
    }
  }
  return []
}

// ──────────────────────────────────────────────────────────────────────────
// Telemetry — live records  (THE FIX: handles both shapes + both names)
// ──────────────────────────────────────────────────────────────────────────
export async function getLiveTelemetry(
  tenantId: string,
): Promise<{ records: TelemetryRecord[]; totalInLedger: number }> {
  try {
    const raw = await gwFetch<unknown>(
      `/api/telemetry/live?tenant_id=${encodeURIComponent(tenantId)}`)

    // Extract total_in_ledger before unwrapping the array
    let totalInLedger = 0
    if (raw && typeof raw === 'object' && !Array.isArray(raw)) {
      const obj = raw as Record<string, unknown>
      if (typeof obj.total_in_ledger === 'number') totalInLedger = obj.total_in_ledger
    }

    const list = unwrapList(raw)
    if (totalInLedger === 0) totalInLedger = list.length

    const records = list.map(r => {
      const wattage = Number(r.Actual_Wattage ?? r.ActualWattage ?? 0)
      const carbon  = Number(r.gCO2e ?? r.CarbonDebt_gCO2 ?? 0)
      const ts      = String(r.Timestamp ?? r.SealedAt ?? '')
      const src     = String(r.Source ?? '')
      const ds      = String(r.DataSource ?? '')
      let infra     = String(r.InfraType ?? '')
      if (!infra) {
        if      (ds === 'CLOUD_DISCOVERY') infra = 'AWS Cloud'
        else if (ds === 'REDFISH_BMC')     infra = 'BMC Redfish'
        else if (src.startsWith('i-'))     infra = 'AWS Cloud'
        else                                infra = 'Edge Agent'
      }

      return {
        ...r,
        TenantID:         String(r.TenantID ?? tenantId),
        Source:           src,
        GridID:           String(r.GridID ?? 'AB'),
        Timestamp:        ts,
        Actual_Wattage:   wattage,
        gCO2e:            carbon,
        InfraType:        infra,
        // Keep legacy aliases populated too
        ActualWattage:    wattage,
        CarbonDebt_gCO2:  carbon,
        DataSource:       ds || (infra.includes('Cloud') ? 'CLOUD_DISCOVERY' : 'EDGE_AGENT'),
        SealedAt:         ts,
      } as TelemetryRecord
    })
    return { records, totalInLedger }
  } catch (e) {
    console.error('getLiveTelemetry failed:', e)
    return { records: [], totalInLedger: 0 }
  }
}

// ──────────────────────────────────────────────────────────────────────────
// Grid status
// ──────────────────────────────────────────────────────────────────────────
export async function getLiveGridData(): Promise<GridSnapshot[]> {
  try {
    const raw = await gwFetch<unknown>(`/api/grid-status`)
    const list = unwrapList(raw)
    return list.map(g => ({
      ...g,
      GridID:           String(g.GridID ?? ''),
      CurrentIntensity: Number(g.CurrentIntensity ?? g.CarbonIntensity ?? 0),
      CarbonIntensity:  Number(g.CarbonIntensity ?? g.CurrentIntensity ?? 0),
      DataQuality:      String(g.DataQuality ?? g.data_quality ?? ''),
    })) as GridSnapshot[]
  } catch (e) {
    console.error('getLiveGridData failed:', e)
    return []
  }
}

// ──────────────────────────────────────────────────────────────────────────
// Incidents
// ──────────────────────────────────────────────────────────────────────────
export async function listIncidents(
  tenantId: string,
  status?: 'OPEN' | 'CLOSED'
): Promise<Incident[]> {
  const q = new URLSearchParams({ tenant_id: tenantId })
  if (status) q.set('status', status)
  try {
    const raw = await gwFetch<unknown>(`/api/incidents?${q.toString()}`)
    return unwrapList(raw) as unknown as Incident[]
  } catch (e) {
    console.error('listIncidents failed:', e)
    return []
  }
}

export async function recordIncidentAction(
  tenantId: string, incidentId: string, action: string, actor: string,
): Promise<void> {
  await gwFetch<unknown>(`/api/incidents/${incidentId}/actions`, {
    method: 'POST',
    body: JSON.stringify({ tenant_id: tenantId, action, actor }),
  })
}

export async function closeIncident(
  tenantId: string, incidentId: string, actor: string, reason: string,
): Promise<void> {
  await gwFetch<unknown>(`/api/incidents/${incidentId}/close`, {
    method: 'POST',
    body: JSON.stringify({ tenant_id: tenantId, actor, reason }),
  })
}

// ──────────────────────────────────────────────────────────────────────────
// Reports
// ──────────────────────────────────────────────────────────────────────────
export async function generateReport(
  tenantId: string, dateFrom: string, dateTo: string, frameworks: string[],
): Promise<{ ok: boolean; download_url?: string; report_id?: string; records?: number }> {
  const r = await fetch(`${API_BASE}/api/reports/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      tenant_id: tenantId, date_from: dateFrom, date_to: dateTo,
      format: 'PDF', frameworks,
    }),
    cache: 'no-store',
  })
  if (!r.ok) throw new Error(`HTTP ${r.status} — report generation failed`)
  try {
    const d = await r.json()
    return { ok: true, download_url: d.download_url, report_id: d.report_id, records: d.records }
  } catch {
    return { ok: true }
  }
}

export async function getLatestReport(tenantId: string): Promise<{
  status: string; download_url?: string; report_id?: string
}> {
  return gwFetch<{ status: string; download_url?: string; report_id?: string }>(
    `/api/reports/latest?tenant_id=${encodeURIComponent(tenantId)}`)
}
